name: Security Check

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:
  push:
    paths:
      - 'requirements.txt'
      - 'requirements-*.txt'
      - 'pyproject.toml'
      - 'setup.py'

jobs:
  security-audit:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run security scan
      run: |
        pip install pip-audit safety
        
        # 執行安全掃描並生成報告
        echo "## Security Scan Report - $(date)" | tee security-report.md
        echo "" | tee -a security-report.md
        
        echo "### pip-audit results:" | tee -a security-report.md
        pip-audit --desc >> security-report.md 2>&1 || echo "Scan completed with warnings" >> security-report.md
        
        echo "" | tee -a security-report.md
        echo "### safety check results:" | tee -a security-report.md
        safety check >> security-report.md 2>&1 || echo "Check completed with warnings" >> security-report.md
        
        echo "" | tee -a security-report.md
        echo "✅ Security scan completed. Review the report for any recommendations." | tee -a security-report.md
    
    - name: Upload security reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: security-reports
        path: |
          security-report.md
        retention-days: 30